site_name: ndarray
site_url: https://ndarray-rust.github.io/ndarray
repo_url: https://github.com/rust-ndarray/ndarray
nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - For NumPy Users: numpy.md
  - Explanations:
      - Array Types: explain/types.md
      - Panics: explain/panics.md
      - Binary Operations: explain/binary-ops.md
  - How-To Guides:
      - Slicing: how-to/slice.md
      - Iteration: how-to/iterate.md
      - Writing Functions: how-to/functions.md
      - Broadcasting: how-to/broadcast.md
  - Features Flags:
      - no_std Support: features/no-std.md
      - Serialization with serde: features/serde.md
      - Approximate Equality with approx: features/approx.md
      - Parallelization with rayon: features/rayon.md
      - BLAS Support: features/blas.md
      - Threading matrixmultiply: features/mm-threading.md
      - Portable Atomics Critical: features/pacs.md
  - ndarray Ecosystem:
      - Integration with rand: ecosystem/rand.md
      - Linear Algebra: ecosystem/linalg.md
  - Glossary: glossary.md

theme:
  name: material

  features:
    - content.code.copy # Code copying
    - navigation.sections # Unfold sections in navigation

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  version:
    provider: mike
