//! Array reference structures.

use core::{
    fmt::Debug,
    ops::{Deref, DerefMut},
};

/// A raw reference type for arrays.
///
/// This is the most fundamental multidimensional array type.
/// Its data is not guaranteed to be safely readable, as it may not be aligned or uniquely owned.
/// Critically, just like [`RefBase`], this type is impossible to construct directly, and can only
/// be created through the [`crate::core::array::RawArrayViewBase`] or [`crate::core::array::ArrayBase`]
/// types.
///
/// Instead of being parameterized by the full backend, this is just parameterized by
/// `R` for the backend's reference type. Many backends will share one reference
/// type (e.g., all dynamically-allocated CPU-based backends, and probably more).
/// It's much more ergonomic to be able to make blanket implementations based on the
/// reference type than the entire backend.
///
/// # Safety
/// Although this type is meant to be as minimal as possible, it must maintain some safety invariants.
/// Implementors of the necessary traits for extending `RawRefBase` must maintain these invariants;
/// traits that can break these invariants are marked `unsafe`.
///
/// Constraints 2–5 are carefully designed such that if they're upheld for the
/// array, they're also upheld for any subset of axes of the array as well as
/// slices/subviews/reshapes of the array. This is important for iterators that
/// produce subviews (and other similar cases) to be safe without extra (easy to
/// forget) checks for zero-length axes. Constraint 1 is similarly upheld for
/// any subset of axes and slices/subviews/reshapes, except when removing a
/// zero-length axis (since if the other axes are non-zero-length, that would
/// allow accessing elements that should not be possible to access).
///
/// ## Data lifetime
/// The `storage` must always refer to a data buffer whose lifetime is longer than the raw reference struct,
/// and `layout` must be consistent with that data buffer, i.e., they should not represent any data outside
/// of the buffer.
///
/// ## Aliasing
/// Aliasing behavior depends upon whether this type is mutably or immutably borrowed.
/// Given `raw_ref` as a `RawRefBase`, `&mut raw_ref` will not have any aliasing indices.
/// However, `&raw_ref` may have aliasing indices. In practice, this invariant is enforced
/// by the [`super::Uniqueable`] trait; however, it is important to understand the
/// distinction for the proper use of `RawRefBase`s.
///
/// ## Non-Null
/// The pointer or other referencing type that points to the data underlying this type must always
/// be non-null
///
/// ## Offset Rules
/// The pointer or other referencing type must also be safe to offset, even by zero.
///
/// It must be safe to offset the pointer repeatedly along all axes
/// and calculate the `count`s for the `.offset()` calls without overflow,
/// even if the array is empty or the elements are zero-sized.
///
/// More specifically, the set of all possible (signed) offset counts
/// relative to `storage` can be determined by the following (the casts and
/// arithmetic must not overflow):
/// ```rust
/// /// Returns all the possible offset `count`s relative to `storage`.
/// fn all_offset_counts(shape: &[usize], strides: &[isize]) -> BTreeSet<isize> {
///     assert_eq!(shape.len(), strides.len());
///     let mut all_offsets = BTreeSet::<isize>::new();
///     all_offsets.insert(0);
///     for axis in 0..shape.len() {
///         let old_offsets = all_offsets.clone();
///         for index in 0..shape[axis] {
///             assert!(index <= isize::MAX as usize);
///             let off = (index as isize).checked_mul(strides[axis]).unwrap();
///             for &old_offset in &old_offsets {
///                 all_offsets.insert(old_offset.checked_add(off).unwrap());
///             }
///         }
///     }
///     all_offsets
/// }
/// ```
///
/// Note that it must be safe to offset the pointer *repeatedly* along all
/// axes, so in addition for it being safe to offset the pointer by each of these
/// counts, the difference between the least and greatest address reachable
/// by these offsets in units of `A` and in units of bytes must not be
/// greater than `isize::MAX`.
///
/// In other words,
///
/// * All possible pointers generated by moving along all axes must be in
///   bounds or one byte past the end of a single allocation with element
///   type `A`. The only exceptions are if the array is empty or the element
///   type is zero-sized. In these cases, `ptr` may be dangling, but it must
///   still be safe to [`.offset()`] the pointer along the axes.
///
/// * The offset in units of bytes between the least address and greatest
///   address by moving along all axes must not exceed `isize::MAX`. This
///   constraint prevents the computed offset, in bytes, from overflowing
///   `isize` regardless of the starting point due to past offsets.
///
/// * The offset in units of `A` between the least address and greatest
///   address by moving along all axes must not exceed `isize::MAX`. This
///   constraint prevents overflow when calculating the `count` parameter to
///   [`.offset()`] regardless of the starting point due to past offsets.
///
/// For example, if the shape is [2, 0, 3] and the strides are [3, 6, -1],
/// the offsets of interest relative to `ptr` are -2, -1, 0, 1, 2, 3. So,
/// `ptr.offset(-2)`, `ptr.offset(-1)`, …, `ptr.offset(3)` must be pointers
/// within a single allocation with element type `A`; `(3 - (-2)) *
/// size_of::<A>()` must not exceed `isize::MAX`, and `3 - (-2)` must not
/// exceed `isize::MAX`. Note that this is a requirement even though the
/// array is empty (axis 1 has length 0).
///
/// A dangling pointer can be used when creating an empty array, but this
/// usually means all the strides have to be zero. A dangling pointer that
/// can safely be offset by zero bytes can be constructed with
/// `::std::ptr::NonNull::<A>::dangling().as_ptr()`. (It isn't entirely clear
/// from the documentation that a pointer created this way is safe to
/// `.offset()` at all, even by zero bytes, but the implementation of
/// `Vec<A>` does this, so we can too. See rust-lang/rust#54857 for details.)
///
/// ## Size Limit
/// The product of non-zero axis lengths must not exceed `isize::MAX`. (This
/// also implies that the length of any individual axis must not exceed
/// `isize::MAX`, and an array can contain at most `isize::MAX` elements.)
/// This constraint makes various calculations easier because they don't have
/// to worry about overflow and axis lengths can be freely cast to `isize`.
#[derive(Debug)]
pub struct RawRefBase<L, R> {
    layout: L,
    storage: R,
}

impl<L, R> RawRefBase<L, R> {
    pub fn layout(&self) -> &L {
        &self.layout
    }

    pub fn storage(&self) -> &R {
        &self.storage
    }

    pub(super) unsafe fn new_unchecked(storage: R, layout: L) -> Self {
        Self { layout, storage }
    }

    /// Move the layout of this reference and attach a new storage.
    ///
    /// # Safety
    /// Callers of this function must ensure that the new storage provided
    /// is compatible with the array's existing `layout` and maintains the
    /// invariants described in the documentation for [`RawRefBase`].
    pub unsafe fn with_storage(self, storage: R) -> Self {
        Self {
            layout: self.layout,
            storage,
        }
    }

    /// Move the storage of this reference and attach a new layout.
    ///
    /// # Safety
    /// Callers of this function must ensure that the new layout provided
    /// is compatible with the array's existing `storage` and maintains the
    /// invariants described in the documentation for [`RawRefBase`].
    pub unsafe fn with_layout<Y>(self, layout: Y) -> RawRefBase<Y, R> {
        RawRefBase {
            layout,
            storage: self.storage,
        }
    }
}

/// A reference type for arrays.
///
/// Data is always aligned and, when received as a mutable reference (`&mut RefBase`),
/// uniquely held and therefore safe to mutate.
///
/// See [`RawRefBase`] for why this is parameterized by `R` and not by the backend.
///
/// # Safety
/// Like `RawRefBase`, the `RefBase` must maintain a number of additional invariants:
/// * Its data must be aligned
/// * When received as a mutable reference (`&mut RefBase`) its data must be uniquely owned
/// and therefore safe to mutate (in addition to the `RawRefBase` requirement that it is
/// non-aliasing)
#[derive(Debug)]
pub struct RefBase<L, R>(RawRefBase<L, R>);

impl<L, R> RefBase<L, R> {
    pub unsafe fn new_unchecked(storage: R, layout: L) -> Self {
        Self {
            0: RawRefBase::new_unchecked(storage, layout),
        }
    }

    pub unsafe fn with_layout<Y>(self, layout: Y) -> RefBase<Y, R> {
        RefBase {
            0: self.0.with_layout(layout)
        }
    }

    pub unsafe fn with_storage(self, storage: R) -> Self {
        Self {
            0: self.0.with_storage(storage)
        }
    }
}

impl<L, R> Deref for RefBase<L, R> {
    type Target = RawRefBase<L, R>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<L, R> DerefMut for RefBase<L, R> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

/// Blanket AsRef implementation, as instructed by the Rust documentation.
impl<L, R, T> AsRef<T> for RefBase<L, R>
where
    T: ?Sized,
    <RefBase<L, R> as Deref>::Target: AsRef<T>,
{
    fn as_ref(&self) -> &T {
        self.deref().as_ref()
    }
}
